Coordonnes2D
int Coordonnes2D::m_X
position X
Referenced by getX, setX, Coordonnes2D.
int Coordonnes2D::m_Y
position Y
Referenced by getY, setY, Coordonnes2D.
int Coordonnes2D::m_cadran
cadran de la fenetre
Referenced by getCadran, setCadran, Coordonnes2D.
Coordonnes2D::Coordonnes2D()
Constructeur.
Default constructorConstructeur de la classe Coordonnes2D
References m_X, m_Y.
Coordonnes2D::Coordonnes2D(int X, int Y)
Constructeur.
Constructeur de la classe Coordonnes2D X : coordonnee X a stocker Y : coordonnee Y a stocker
References m_X, m_Y.
Coordonnes2D::Coordonnes2D(const Coordonnes2D &c)
Constructeur.
Constructeur de copie de la classe Coordonnes2D c : reference sur l'element a copier
References m_X, getX, m_Y, getY, m_cadran, getCadran.
Coordonnes2D::~Coordonnes2D()
Destructeur.
Default destructorDestructeur de la classe Coordonnes2D
int Coordonnes2D::getX() const
Getter.
Getter de l'attribut m_X de la classe Coordonnes2Dl'attribut m_X de la classe Coordonnes2D
References m_X.
Referenced by Coordonnes2D, Graphe::Graphe, TERObserver::setup, TERObserver::synchronizeMap, TERObserver::map2Repast.
int Coordonnes2D::getY() const
Getter.
Getter de l'attribut m_Y de la classe Coordonnes2Dl'attribut m_Y de la classe Coordonnes2D
References m_Y.
Referenced by Coordonnes2D, Graphe::Graphe, TERObserver::setup, TERObserver::synchronizeMap, TERObserver::map2Repast.
int Coordonnes2D::getCadran() const
Getter.
Getter de l'attribut m_cadran de la classe Coordonnes2Dl'attribut m_cadran de la classe Coordonnes2D
References m_cadran.
Referenced by Coordonnes2D.
void Coordonnes2D::setX(int X)
Setter.
Setter de l'attribut m_X de la classe Coordonnes2D
References m_X.
Referenced by TERObserver::setup, TERObserver::synchronizeMap, TERObserver::map2Repast.
void Coordonnes2D::setY(int Y)
Setter.
Setter de l'attribut m_Y de la classe Coordonnes2D
References m_Y.
Referenced by TERObserver::setup, TERObserver::synchronizeMap, TERObserver::map2Repast.
void Coordonnes2D::setCadran(int val)
Setter.
Setter de l'attribut m_cadran de la classe Coordonnes2D
References m_cadran.