Humain
double Humain::m_angle
Angle d'orientation de l'agent
int Humain::posXFichier
Position X de l'agent dans le fichier (colonne)
int Humain::posYFichier
Position Y de l'agent dans le fichier (ligne)
int Humain::posXGL
Position X de l'agent dans la fenetre (pixels)
int Humain::posYGL
Position Y de l'agent dans la fenetre (pixels)
std::vector<int> Humain::cheminX
Tableau des positions X a suivre par l'agent
std::vector<int> Humain::cheminY
Tableau des positions Y a suivre par l'agent
int Humain::etape
indice pour se situer dans le tableau du chemin a suivre
int Humain::typePersonne
Type de personne (JEUNE,ADULTE,PERSONNE AGEE ou MALADE)
bool Humain::sorti
Booleen qui indique si un humain est sorti du batiment
Humain::Humain(repast::AgentId id, repast::relogo::Observer *obs)
Constructeur.
Constructeur de la classe Humain id : Id de l'agent obs : pointeur vers l'Observer qui gere les agents
References randomType.
Humain::Humain(repast::AgentId id, repast::relogo::Observer *obs, const AgentPackage &package)
Constructeur pour le transfert d'agents.
Constructeur de la classe Humain id : Id de l'agent obs : pointeur vers l'Observer qui gere les agents package : archive serialisee qui contient toutes les donnees necessaire pour creer un agent.
virtual Humain::~Humain()
Destructeur.
Destructeur de la classe Humain
void Humain::getPos()
affiche la position d'un humain(coordonnees repast)
void Humain::step()
fonction principale decrivant le comportement de l'agent (execute a chaque tick)
Referenced by TERObserver::go.
void Humain::randomAngle(repast::Properties &props)
genere un angle aleatoire compris entre 0 et 359 (en degre)
props : pointeur sur les proprietes de la simulation(pour le random seed)
Referenced by TERObserver::setup.
int Humain::randomType(repast::Properties &props)
genere un type de personne aleatoire
props : pointeur sur les proprietes de la simulation(pour le random seed) le typedepersonne genere.
Referenced by Humain.
void Humain::afficherPos(Fenetre *fen)
double Humain::getAngle()
recupere l'angle actuel d'un agent
l'angle de l'agent
Referenced by TERObserver::setup, TERObserver::dessinerDecor.
double Humain::rad2deg(double theta)
conversion d'un angle de radians en degre
theta : angle en radians angle en degre.
double Humain::tournerVers(double x, double y)
Calcule l'angle a prendre pour aller au point de coordonnees x/y.
x : coordonne x de l'emplacement ou on veut aller y : coordonne y de l'emplacement ou on veut aller angle vers le point de destination.
int Humain::getXFichier(void) const
Getter.
l'attribut posXFichier de la classe Humain
int Humain::getYFichier(void) const
Getter.
l'attribut posYFichier de la classe Humain
int Humain::getXGL(void) const
Getter.
l'attribut posXGL de la classe Humain
int Humain::getYGL(void) const
Getter.
l'attribut posYGL de la classe Humain
void Humain::setXFichier(int val)
Setter.
val : nouvelle valeur pour l'attribut posXFichier de la classe Humain
void Humain::setYFichier(int val)
Setter.
val : nouvelle valeur pour l'attribut posYFichier de la classe Humain
void Humain::setXGL(int val)
Setter.
val : nouvelle valeur pour l'attribut posXGL de la classe Humain
void Humain::setYGL(int val)
Setter.
val : nouvelle valeur pour l'attribut posYGL de la classe Humain
void Humain::setAngle(double val)
Setter.
val : nouvelle valeur pour l'attribut m_angle de la classe Humain
int Humain::getTypePersonne()
Getter.
l'attribut typePersonne de la classe Humain
Referenced by TERObserver::dessinerDecor, TERObserver::provideContent.
void Humain::setTypePersonne(int val)
int Humain::getEtape()
Getter.
l'attribut etape de la classe Humain
Referenced by TERObserver::provideContent.
bool Humain::getSorti()
Getter.
l'attribut sorti de la classe Humain
Referenced by TERObserver::dessinerDecor.
std::vector<int> Humain::getCheminX()
Getter.
l'attribut cheminX de la classe Humain
Referenced by TERObserver::provideContent.
std::vector<int> Humain::getCheminY()
Getter.
l'attribut cheminY de la classe Humain
Referenced by TERObserver::provideContent.
void Humain::setCheminXY(std::vector< int > cheminX, std::vector< int > cheminY, int etape, bool sorti)
Setter.
cheminX : nouvelle valeur pour l'attribut cheminX de la classe Humain cheminY : nouvelle valeur pour l'attribut cheminY de la classe Humain etape : nouvelle valeur pour l'attribut etape de la classe Humain sorti : nouvelle valeur pour l'attribut sorti de la classe Humain
Referenced by TERObserver::setup, TERObserver::updateAgent.