Node
int Node::m_g
Heuristique G representant la valeur totale du chemin parcourru
int Node::m_h
Heuristique H representant la distance a vol d'oiseau de la position actuelle jusqu'au Node d'arrivee
int Node::m_f
Somme de G et H, F = H + G
int Node::m_X
Position X
int Node::m_Y
Position Y
bool Node::m_walkable
Boolean representant si le Node est un mur ou pas
Node* Node::m_parent
pointeur sur le Node parent
Node::Node()
Constructeur.
Constructeur de la classe Node
Node::~Node()
Destructeur.
Destructeur de la classe Node
bool Node::estEgal(Node const &b) const
Compare deux objets de type Node.
b : node a comparer au Node actuel un boolean idiquant si les deux nodes sont egaux.
void Node::setParent(Node *val)
Setter de l'attribut Parent de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Pathfinder::findPath.
Node * Node::getParent()
Getter de l'attribut m_parent de la classe Node.
valeur de l'attribut m_parent de la classe Node
Referenced by Pathfinder::findPath.
void Node::setWalkable(bool val)
Setter de l'attribut m_walkable de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Graphe::Graphe.
void Node::setG(int val)
Setter de l'attribut m_G de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Pathfinder::findPath.
void Node::setF(int val)
Setter de l'attribut m_F de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Pathfinder::findPath.
void Node::setH(int val)
Setter de l'attribut m_h de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Pathfinder::findPath.
void Node::setX(int val)
Setter de l'attribut m_X de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Graphe::Graphe.
void Node::setY(int val)
Setter de l'attribut m_Y de la classe Node.
val : valeur de l'attribut a modifier
Referenced by Graphe::Graphe.
bool Node::getWalkable()
Getter de l'attribut m_walkable de la classe Node.
valeur de l'attribut m_walkable de la classe Node
Referenced by Pathfinder::findPath.
int Node::getG()
Getter de l'attribut m_G de la classe Node.
valeur de l'attribut m_G de la classe Node
Referenced by Pathfinder::findPath.
int Node::getF()
Getter de l'attribut m_F de la classe Node.
valeur de l'attribut m_F de la classe Node
int Node::getH()
Getter de l'attribut m_H de la classe Node.
valeur de l'attribut m_H de la classe Node
int Node::getX()
Getter de l'attribut m_X de la classe Node.
valeur de l'attribut m_X de la classe Node
Referenced by Graphe::calculSortie, Pathfinder::findPath.
int Node::getY()
Getter de l'attribut m_Y de la classe Node.
valeur de l'attribut m_Y de la classe Node
Referenced by Graphe::calculSortie, Pathfinder::findPath.