Couleur
Uint8 Couleur::m_R
quantite de rouge
Referenced by Couleur, getR, setColor, setR, setRGB.
Uint8 Couleur::m_G
quantite de vert
Referenced by Couleur, getG, setColor, setG, setRGB.
Uint8 Couleur::m_B
quantite de bleu
Referenced by Couleur, getB, setColor, setB, setRGB.
SDL_Color Couleur::m_color
structure de donnee SDL pour representer une couleur
Referenced by Couleur, getSDLColor, setColor, setSDLColor, setR, setG, setB, setRGB.
Uint32 Couleur::m_color_uint32
structure de donnee SDL pour representer une couleur
Referenced by getColor.
Couleur::Couleur(Uint8 R, Uint8 G, Uint8 B)
Constructeur.
Default constructorConstructeur de la classe Couleur R : quantite de rouge G : quantite de vert B : quantite de bleu
References m_color, m_R, m_G, m_B.
Couleur::~Couleur()
Destructeur.
Destructeur de la classe Couleur
Uint32 Couleur::getColor()
Getter.
GettersGetter de l'attribut m_color_uint32 de la classe CouleurGetters
References m_color_uint32.
SDL_Color Couleur::getSDLColor()
Getter.
Getter de l'attribut m_color de la classe Couleur
References m_color.
Uint8 Couleur::getR()
Getter.
Getter de l'attribut m_R de la classe Couleur
References m_R.
Referenced by Fenetre::dessinerTriangle.
Uint8 Couleur::getG()
Getter.
Getter de l'attribut m_G de la classe Couleur
References m_G.
Referenced by Fenetre::dessinerTriangle.
Uint8 Couleur::getB()
Getter.
Getter de l'attribut m_B de la classe Couleur
References m_B.
Referenced by Fenetre::dessinerTriangle.
void Couleur::setColor(Uint32 val)
Setter.
SettersSetter de l'attribut m_color_uint32 de la classe Couleur val : valeur a attribuer a l'attribut m_color_uint32 de la classe Couleur Setters
References m_color, m_R, m_G, m_B.
void Couleur::setSDLColor(SDL_Color val)
Setter.
Setter de l'attribut m_color de la classe Couleur val : valeur a attribuer a l'attribut m_color de la classe Couleur
References m_color.
void Couleur::setR(Uint8 val)
Setter.
Setter de l'attribut m_R de la classe Couleur val : valeur a attribuer a l'attribut m_R de la classe Couleur
References m_R, m_color.
void Couleur::setG(Uint8 val)
Setter.
Setter de l'attribut m_G de la classe Couleur val : valeur a attribuer a l'attribut m_G de la classe Couleur
References m_G, m_color.
void Couleur::setB(Uint8 val)
Setter.
Setter de l'attribut m_B de la classe Couleur val : valeur a attribuer a l'attribut m_B de la classe Couleur
References m_B, m_color.
void Couleur::setRGB(Uint8 valR, Uint8 valG, Uint8 valB)
Setter.
Setter des attributs m_R , m_G , m_B de la classe Couleur valR : valeur a attribuer a l'attribut m_R de la classe Couleur valG : valeur a attribuer a l'attribut m_G de la classe Couleur valB : valeur a attribuer a l'attribut m_B de la classe Couleur
References m_R, m_G, m_B, m_color.